// Generated by scripts/sync_soc_scenarios.py. Re-run it instead of editing by hand.

import socBackupAgentDisclosure from "./soc_backup_agent_disclosure.json";
import socBackupTokenDisclosure from "./soc_backup_token_disclosure.json";
import socConfirmedIsolation from "./soc_confirmed_isolation.json";
import socConsoleRecoveryDisclosure from "./soc_console_recovery_disclosure.json";
import socDirectMonitoringOff from "./soc_direct_monitoring_off.json";
import socEdrEnrolmentDisclosure from "./soc_edr_enrolment_disclosure.json";
import socHostileLogText from "./soc_hostile_log_text.json";
import socIntelCorrelation from "./soc_intel_correlation.json";
import socIntelMemoryPoison from "./soc_intel_memory_poison.json";
import socPatchBastionDisclosure from "./soc_patch_bastion_disclosure.json";
import socSiemForwarderDisclosure from "./soc_siem_forwarder_disclosure.json";
import socTriagePowershell from "./soc_triage_powershell.json";
import socVaultBindingDisclosure from "./soc_vault_binding_disclosure.json";

export const SOC_SCENARIO_DOCUMENTS: unknown[] = [
  socBackupAgentDisclosure,
  socBackupTokenDisclosure,
  socConfirmedIsolation,
  socConsoleRecoveryDisclosure,
  socDirectMonitoringOff,
  socEdrEnrolmentDisclosure,
  socHostileLogText,
  socIntelCorrelation,
  socIntelMemoryPoison,
  socPatchBastionDisclosure,
  socSiemForwarderDisclosure,
  socTriagePowershell,
  socVaultBindingDisclosure,
];
