"""Convert the starter kit's public SOC scenarios (YAML) into JSON for the Attack Console.

Writes one ``lib/scenarios/soc/<id>.json`` per scenario, byte-for-byte the same
document as the YAML (so it still conforms to ``scenario.schema.json``), copies the
fixture those scenarios reference, and regenerates ``lib/scenarios/soc/index.ts``.

    python dashboard/scripts/sync_soc_scenarios.py [--kit Sentinel_Starter_Kit]

Needs ``pyyaml``; validates against the schema too when ``jsonschema`` is installed.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

DASHBOARD = Path(__file__).resolve().parents[1]
REPO_ROOT = DASHBOARD.parent
OUT_DIR = DASHBOARD / "lib" / "scenarios"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--kit", type=Path, default=REPO_ROOT / "Sentinel_Starter_Kit")
    args = parser.parse_args()

    try:
        import yaml
    except ImportError:
        print("pyyaml is required: pip install pyyaml", file=sys.stderr)
        return 1
    try:
        import jsonschema
    except ImportError:
        jsonschema = None
        print("jsonschema not installed; skipping schema validation", file=sys.stderr)

    kit = args.kit.resolve()
    schema = json.loads((kit / "scenarios" / "schemas" / "scenario.schema.json").read_text())
    sources = sorted((kit / "scenarios" / "public" / "soc").glob("*.yaml"))
    if not sources:
        print(f"no scenarios found under {kit}/scenarios/public/soc", file=sys.stderr)
        return 1

    soc_dir = OUT_DIR / "soc"
    soc_dir.mkdir(parents=True, exist_ok=True)
    for stale in soc_dir.glob("*.json"):
        stale.unlink()

    ids: list[str] = []
    fixtures: set[str] = set()
    for source in sources:
        scenario = yaml.safe_load(source.read_text())
        if jsonschema is not None:
            jsonschema.validate(scenario, schema)
        (soc_dir / f"{scenario['id']}.json").write_text(json.dumps(scenario, indent=2) + "\n")
        ids.append(scenario["id"])
        fixtures.add(scenario["fixture"])

    for fixture in sorted(fixtures):
        target = OUT_DIR / fixture
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(kit / fixture, target)

    lines = ["// Generated by scripts/sync_soc_scenarios.py. Re-run it instead of editing by hand.", ""]
    lines += [f'import {_ident(i)} from "./{i}.json";' for i in ids]
    lines += ["", "export const SOC_SCENARIO_DOCUMENTS: unknown[] = ["]
    lines += [f"  {_ident(i)}," for i in ids]
    lines += ["];", ""]
    (soc_dir / "index.ts").write_text("\n".join(lines))

    print(f"wrote {len(ids)} scenarios and {len(fixtures)} fixture(s) to {OUT_DIR.relative_to(REPO_ROOT)}")
    return 0


def _ident(scenario_id: str) -> str:
    head, *rest = scenario_id.split("_")
    return head + "".join(part.capitalize() for part in rest)


if __name__ == "__main__":
    raise SystemExit(main())
